### ISSUE TITLE
Height isn't equal to iOS 7 Safari progress bar

### ISSUE THREAD

**Issue by oemera** [sgryschuk/SGNavigationProgress#2]
The height of the progress bar isn't equal to the iOS 7 Safari. Safari uses 2.5 points height and this project uses just 1 point.

Fixing this is a character-change and not a big deal but it is a big deal when it comes to coherent design / interfaces. People will recognizes it better and know more what it is.
Plus I found it harder to see the bar with just 1 point in height but with 2.5 points you can see it _better_

**Comment by oemera** [comment]
Added commit for change in own fork. I can open a pull request if the change is good

**Comment by sgryschuk** [comment]
Looks good to me, if you make a pull request I'll merge it in.
