### ISSUE TITLE
Cancel option should be added

### ISSUE THREAD

**Issue by oemera** [sgryschuk/SGNavigationProgress#4]
On the progress in iOS 7 Safari there is also an animation for canceling the current progress. At the moment in this project we just have the option to finish the progress bar.

Finishing a progress bar even on failure can lead to weird expectations. It would be more coherent and a better UX to have a cancel animation like Safari in iOS 7.

The cancel-animation is simple and just fades the current progress bar out of the navigation bar (for a example: open web page in iOS 7 Safari and cancel loading).

What do you think? I can add it and create a pull request.

**Comment by sgryschuk** [comment]
Sounds great, go for it!
